# Generated by Django 4.2.19 on 2025-03-17 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='截图')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '图片上传',
                'verbose_name_plural': '图片上传',
            },
        ),
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脸谱名称')),
                ('kuanhe', models.IntegerField(verbose_name='宽和')),
                ('badao', models.IntegerField(verbose_name='霸道')),
                ('tiandan', models.IntegerField(verbose_name='恬淡')),
                ('haosheng', models.IntegerField(verbose_name='好胜')),
                ('chaoran', models.IntegerField(verbose_name='超然')),
                ('rushi', models.IntegerField(verbose_name='入世')),
                ('duoqing', models.IntegerField(verbose_name='多情')),
                ('wuqing', models.IntegerField(verbose_name='无情')),
                ('suihe', models.IntegerField(verbose_name='随和')),
                ('jiao', models.IntegerField(verbose_name='桀骜')),
                ('gengzhi', models.IntegerField(verbose_name='耿直')),
                ('linglong', models.IntegerField(verbose_name='玲珑')),
                ('gengu', models.IntegerField(verbose_name='根骨')),
                ('hongyi', models.IntegerField(verbose_name='弘毅')),
                ('danshi', models.IntegerField(verbose_name='胆识')),
                ('shenshou', models.IntegerField(verbose_name='身手')),
                ('tipo', models.IntegerField(verbose_name='体魄')),
                ('ruizhi', models.IntegerField(verbose_name='睿智')),
                ('tongqu', models.IntegerField(verbose_name='童趣')),
                ('fuyuan', models.IntegerField(verbose_name='福缘')),
                ('jiaoji', models.IntegerField(verbose_name='交际')),
                ('meili', models.IntegerField(verbose_name='魅力')),
                ('mingqi', models.IntegerField(verbose_name='名气')),
                ('weiwang', models.IntegerField(verbose_name='威望')),
                ('collection_info', models.TextField(verbose_name='收集属性信息')),
                ('color', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': '脸谱',
                'verbose_name_plural': '脸谱',
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_time', models.DateTimeField(auto_now_add=True)),
                ('mask_name', models.CharField(max_length=5000)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('query_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '查询历史',
                'verbose_name_plural': '查询历史',
                'ordering': ['-query_time'],
            },
        ),
    ]
