# Generated by Django 4.2.19 on 2025-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
