from django import forms

class MaskCompareForm(forms.Form):
    kuanhe = forms.IntegerField(label='宽和', required=False)
    badao = forms.IntegerField(label='霸道', required=False)
    tiandan = forms.IntegerField(label='恬淡', required=False)
    haosheng = forms.IntegerField(label='好胜', required=False)
    chaoran = forms.IntegerField(label='超然', required=False)
    rushi = forms.IntegerField(label='入世', required=False)
    duoqing = forms.IntegerField(label='多情', required=False)
    wuqing = forms.IntegerField(label='无情', required=False)
    suihe = forms.IntegerField(label='随和', required=False)
    jiao = forms.IntegerField(label='桀骜', required=False)
    gengzhi = forms.IntegerField(label='耿直', required=False)
    linglong = forms.IntegerField(label='玲珑', required=False)
    gengu = forms.IntegerField(label='根骨', required=False)
    hongyi = forms.IntegerField(label='弘毅', required=False)
    danshi = forms.IntegerField(label='胆识', required=False)
    shenshou = forms.IntegerField(label='身手', required=False)
    tipo = forms.IntegerField(label='体魄', required=False)
    ruizhi = forms.IntegerField(label='睿智', required=False)
    tongqu = forms.IntegerField(label='童趣', required=False)
    fuyuan = forms.IntegerField(label='福缘', required=False)
    jiaoji = forms.IntegerField(label='交际', required=False)
    meili = forms.IntegerField(label='魅力', required=False)
    mingqi = forms.IntegerField(label='名气', required=False)
    weiwang = forms.IntegerField(label='威望', required=False) 